@extends('voyager::master')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <h3>Name: {{ $apply->name }}</h3>
                <h3>Cause: {{ $apply->causes->name }} </h3>
                <h3>Requarment Amount: {{ $apply->required_amount }} {{ $apply->summ_type->name }} </h3>
                <h3>Tell: {{ $apply->phone }} </h3>
                <h3>Address: {{ $apply->address }} </h3>
                <h3>Description: {{ $apply->description }} </h3>
            </div>
            <div class="col-sm-4">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam totam cum ea consequatur aspernatur, eaque recusandae facilis ipsa vel illum ullam quaerat velit earum ab accusantium, voluptatibus fuga quia quasi temporibus sint voluptas! Nam at aliquid architecto aut, hic, autem consectetur adipisci doloremque quaerat tenetur ea cumque molestias quia, ipsa totam non ipsum amet? Exercitationem fuga vel nisi similique corrupti veritatis porro iste. Laborum voluptatum atque alias quos itaque, sed est assumenda commodi nesciunt, enim neque accusamus maiores. Placeat esse voluptas ullam sint, vel veniam architecto saepe voluptates. Inventore maiores animi natus! Temporibus debitis veritatis vitae impedit accusamus culpa ratione necessitatibus in sapiente maiores sit placeat molestias incidunt rem ab ullam blanditiis, pariatur dolorum magnam laboriosam, commodi ex aliquam. Ipsam atque tenetur maiores et consectetur maxime quae sequi. Aut minus autem non molestias provident pariatur rem exercitationem magnam modi iusto eos, consectetur laborum. Deleniti neque consequuntur harum ex, cumque delectus, repudiandae minus aliquid nulla sed magni! Quod suscipit, minus facilis molestias sapiente dolor aspernatur porro accusamus sed dignissimos, illo quasi! Ad doloremque impedit et non autem laudantium quidem magnam libero necessitatibus totam in a maxime qui ipsam voluptatem, quo odit similique saepe iusto earum blanditiis harum, quisquam deleniti asperiores. Officiis corrupti quasi sed vitae totam. Porro amet provident ea eum tempora ducimus a voluptates quo alias, adipisci, aliquam quisquam accusamus magnam facere esse delectus error dicta. Totam autem molestiae corporis accusamus maxime eligendi sit quisquam ut maiores sapiente id molestias debitis nostrum vel nihil, beatae quia modi quos voluptate dolorum. Dolorum nisi exercitationem inventore beatae esse! Accusantium ex repellat velit libero expedita, hic ipsam iure harum, magnam doloribus inventore itaque molestias, quam voluptatibus sint sunt nulla error totam necessitatibus modi. Officiis ullam vitae alias aliquam quibusdam cum asperiores, earum qui delectus impedit optio maxime voluptates ea. Saepe alias ea repellat.
            </div>
            <div class="col-sm-4">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias iusto unde a dolores quod veritatis harum ab minus atque temporibus saepe in sint dolore fuga reprehenderit laborum molestiae magnam earum, ipsam quae eaque ea alias voluptatibus? Ad, similique. Eaque veritatis harum vero neque ipsam, qui, dicta quibusdam architecto numquam quod sit! Soluta obcaecati temporibus culpa fugiat qui molestias quod odio rerum earum, error quasi assumenda aut minus nemo eos dolor vero tenetur mollitia tempore magni et? Quis quasi eos inventore facilis at quam velit tempora minima enim, eaque laborum? Ipsam, ducimus? In, obcaecati? Ipsum necessitatibus iste voluptate tempore pariatur cupiditate libero temporibus nulla similique! Dolores eveniet vero esse repellendus repellat! Odio, consequatur est molestias tempore quod accusamus unde dolorum atque, inventore placeat culpa a, assumenda totam! Minima, ipsam enim quas delectus sed, repudiandae est ad voluptate, maiores totam laborum dolorum quidem saepe dolores. Voluptas quae facere, distinctio placeat illo quasi esse culpa dolore labore quaerat? Placeat porro quia ipsa rem maiores, minima aperiam ea quos officiis beatae iusto ipsum soluta nisi alias amet ab ratione sequi autem provident incidunt quaerat dolores numquam? Harum qui, alias eveniet ut, modi cupiditate autem officia molestiae eos porro vel veritatis mollitia dolorem quasi voluptatibus rerum doloremque! Praesentium rerum itaque hic illo nostrum! Incidunt, porro dignissimos nostrum modi earum sunt quis quibusdam, fugiat nisi quod doloremque alias dolore, dolorem corporis sint ipsam voluptatem tenetur placeat vitae optio. Reprehenderit in harum temporibus voluptates accusamus rem modi natus. Eius corrupti nemo nam molestiae nostrum, magnam fugiat assumenda rerum mollitia incidunt blanditiis sapiente ipsa quasi? Soluta nesciunt excepturi sunt, fugit tempora eum cum accusantium tempore quod ipsum voluptatum, illum ad iure officiis voluptas praesentium, hic nam quibusdam saepe neque. Molestias nihil dolore adipisci inventore perspiciatis a quisquam temporibus. Nemo adipisci et accusantium pariatur nulla culpa est distinctio similique?
            </div>
        </div>
    </div>
@endsection
