@extends('voyager::master')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem natus obcaecati quae repudiandae, culpa sint tenetur neque. Qui obcaecati ex quibusdam, dicta dolorem consectetur, numquam optio, autem non dolore totam cupiditate. Rerum tenetur, quo molestiae sit perspiciatis assumenda consequatur a? Repudiandae similique ex, totam nulla sint temporibus tempore eos distinctio veritatis vitae quisquam excepturi, quam debitis fugiat quae, maxime laborum a fuga possimus consectetur accusamus in sapiente. Accusamus, deleniti! Ut odit voluptate natus voluptates optio sed molestiae eius consequuntur reprehenderit dignissimos beatae sint soluta illum provident quaerat eveniet, aspernatur aliquam at cum dicta! Ab suscipit cumque error, totam earum quo blanditiis, porro ipsum necessitatibus ullam illo alias perferendis at. Nostrum doloribus illo magni sunt delectus quia placeat deserunt dolores aspernatur ducimus molestias nesciunt, inventore iste, explicabo labore iure sed! Similique, dolores quae. Corporis obcaecati vitae quidem cupiditate repudiandae illum quibusdam. Harum neque vel aliquam perspiciatis delectus, corrupti eius odit perferendis cum deleniti officia repellat odio iste velit tempore reprehenderit temporibus corporis ipsa architecto quidem beatae doloribus assumenda totam enim? Rerum rem accusantium consectetur aliquid illum exercitationem iure, inventore eveniet voluptatibus minus autem culpa odit vel animi reprehenderit reiciendis amet ratione tenetur consequatur sit? Doloremque maxime maiores est et, aliquam nesciunt illo repellat tempora officiis ad ratione reiciendis culpa molestias autem sunt atque modi laborum consequatur labore ea cumque cupiditate possimus, eveniet hic? Dolor suscipit, quas facilis cum, harum dicta nostrum temporibus libero reiciendis velit error delectus unde quasi laborum sequi neque asperiores commodi. Temporibus nihil reiciendis atque quo cumque molestiae rerum sapiente impedit sunt ea porro odio, quia dolores illo a unde autem mollitia quam dolorem eius esse tenetur exercitationem minus. Obcaecati repellendus ab assumenda corporis fugiat quia, cum, sint eligendi eos sunt consequatur hic sed consequuntur perferendis dolorum. Mollitia placeat obcaecati maiores! Sit quos vitae aliquid nisi, odit vero!
                <h3>Name {{ $apply->name }}</h3>
            </div>
            <div class="col-lg-6">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur cum ratione rerum, architecto recusandae totam maiores neque ducimus odio, animi, suscipit eligendi repellat tempore ea inventore possimus atque tenetur! Cum perferendis magni quas unde aut cumque officiis tempora! Dignissimos, neque tenetur nihil modi ratione accusantium sit magni earum quas laborum beatae alias quae odit facere molestiae placeat amet sed. Odio aut iusto non facilis. Libero, doloremque consequuntur ullam voluptates dolorem quidem tempora nulla magni vitae expedita minus sequi facere quas consectetur laboriosam qui recusandae quisquam numquam eligendi exercitationem totam quae cumque corporis accusantium? Repellat voluptatum expedita hic officiis labore quam quibusdam harum fugiat minima provident velit perspiciatis repellendus quidem doloribus illo ratione id consequuntur natus consequatur, optio aut fuga enim! Non excepturi blanditiis unde laboriosam facere facilis dolores. Consectetur eius architecto nemo animi voluptatum quibusdam, exercitationem deleniti placeat consequuntur! Accusantium explicabo officia facere, quod temporibus, veritatis obcaecati distinctio ipsa fugit quia blanditiis dignissimos nihil et, doloribus ex eos excepturi praesentium dolores ad autem consectetur dicta esse delectus eligendi! Excepturi earum nesciunt tempora, rerum non, in asperiores recusandae inventore, libero exercitationem mollitia ea vero id ducimus incidunt possimus facilis. Tempora velit quae cumque consequuntur. Earum autem quia assumenda dolores modi fuga qui nobis esse, deleniti a velit saepe sed ullam voluptates tenetur quos voluptatum, magni quas quod doloribus perferendis iusto! Recusandae quidem tempora aliquam, maxime molestias deserunt corporis fugit repudiandae ratione ducimus eveniet alias. Dolorem doloribus harum optio ullam ea porro praesentium distinctio, nemo voluptas! Aperiam necessitatibus maiores quas sequi magni! Magnam deleniti sapiente esse nobis, ratione quos ducimus, dolores in consequatur omnis officiis, rerum architecto pariatur quasi voluptas cupiditate libero. Obcaecati eveniet necessitatibus voluptate, dicta officiis, illo delectus quibusdam esse asperiores qui repellat pariatur ex maiores perspiciatis velit, eius quod et sit amet possimus ullam ad laboriosam maxime? Voluptates, similique?
            </div>
        </div>
    </div>
@endsection
